# Generated by Django 4.2.6 on 2023-10-06 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='user/profile_img/%Y%M%D/', verbose_name='프로필 이미지')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='수정일')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 권한 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='팔로잉')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
