# Generated by Django 4.2.6 on 2023-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': '이메일은 비워둘 수 없습니다.', 'unique': '해당 이메일은 이미 사용중입니다.'}, max_length=255, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': '아이디는 비워둘 수 없습니다.', 'unique': '해당 아이디는 이미 사용중입니다.'}, max_length=30, unique=True, verbose_name='아이디'),
        ),
    ]
