# Generated by Django 4.2.6 on 2023-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_verification_token_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='계정 활성화 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='images/DefaultProfile.png', upload_to='user/profile_img/%Y/%m/%D/', verbose_name='프로필 이미지'),
        ),
    ]
