# Generated by Django 4.2.6 on 2023-10-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wishes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='게시글 제목')),
                ('wish_name', models.CharField(max_length=50, verbose_name='위시 상품명')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('bookmarks', models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='북마크')),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('tags', models.ManyToManyField(related_name='tags', to='wishes.tag', verbose_name='태그')),
            ],
        ),
        migrations.CreateModel(
            name='WishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=wishes.models.image_upload_path)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='wishes.wish')),
            ],
            options={
                'db_table': 'wish_image',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 생성 시각')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wishes.wish', verbose_name='위시')),
            ],
        ),
    ]
